### ISSUE TITLE
Kana found between two kanji produces furigana readings

### ISSUE THREAD

**Issue by ahlec** [obynio/anki-japanese-furigana#12]
When adding furigana to a word with kana between two kanji (eg, `走り去る`), the produced furigana includes the hiragana found between the two kanji (in the example, it produces `走り去[はしりさ]る`).

**Expected behavior:** 走[はし]り去[さ]る (?)

**Comment by obynio** [comment]
This is mostly due to how MeCab handles the kanji and produce the reading. Nothing much we can do here since MeCab development appears to be stalled since a few years.
