### ISSUE TITLE
Possible regression on 2.1.49

### ISSUE THREAD

**Issue by ahlec** [obynio/anki-japanese-furigana#14]
According to the addon comments, one of the recent releases caused 2.1.49 to break:

> In the September 27th update in 2.1.49 no longer works, trouble to fix

I'm guessing the suspect changes would be in #11.

**Comment by ahlec** [comment]
I'm happy to investigate this one in a few days; I was planning to do some additional work this weekend, and if I'm responsible for breaking this, I ought to take ownership of fixing it (or at least investigating if the report's accurate).

**Comment by obynio** [comment]
Yeah, I just fixed it in #15  and released an update on the Anki plugin manager.
