### ISSUE TITLE
Furigana generation breaks the <br> formatting

### ISSUE THREAD

**Issue by kebifurai** [obynio/anki-japanese-furigana#3]
Right now is impossible to generate furigana for multiple lines without messing up the formatting.

**Comment by obynio** [comment]
Hello, yes I am aware of the issue. I did not yet found a way to parse how Anki marks new lines in fields which appears to differ depending of the Anki version. It's on my todo list.

**Comment by obynio** [comment]
Note to myself, also remove the extra space in the resulting text once the parsing by Kakasi is done.

**Comment by obynio** [comment]
Okay @kebifurai, I took a look

* The good news is that i found a way to keep the html formatting while converting the kanjis
* The bad news is that it's not backward compatible with versions older than 2.1.41

I'll try to push an update once I finished cleaning my work 👍

**Comment by obynio** [comment]
Backward compatibility is ensured for the moment. Issue solved with eac2b34b0975ac68d5e1b9b3a43605247bb222a4
