### ISSUE TITLE
Mass generation

### ISSUE THREAD

**Issue by postkevone** [obynio/anki-japanese-furigana#7]
The addon works very well with generating readings while adding a card, but sometimes I need to mass generate readings for decks made by other people.

It would be great if I could generate furigana for an entire deck with one simple button.

**Comment by obynio** [comment]
The furigana generation is done by an external program so it might freeze Anki when bulk editing the cards, so I need to experiment a bit on it before to see if that's doable.

**Comment by yangmillstheory** [comment]
+1 for this. Mass removal would be good too.

**Comment by hillfortgames** [comment]
+1 for me too. I would love this add-On to have a batching option.

**Comment by obynio** [comment]
Hello @yangmillstheory @felixdv @postkevone @hillfortgames 

This feature is now supported in the latest release. Please update your addon.
