### ISSUE TITLE
Furigana only shown in brackets, not above kanji

### ISSUE THREAD

**Issue by emiryyy** [obynio/anki-japanese-furigana#9]
I'm doing single line vocabs from novels I've been reading and the furigana doesn't seem to be hovering over the kanji as shown in your image on the anki web page. I was wondering if I missed a step in terms of setting the add-on up? (sorry I don't know a single line of code here so I'm just really confused)

**Comment by obynio** [comment]
Furigana generated above kanjis use HTML ruby tags. Ruby tags were a thing used by CloneFuriganaTools and inspired many Anki plugins back when Anki was not supporting bracket notation for Furigana.

Think if it as a remnant of the Anki's past. It's 2022 and Anki now supports bracket notation so I decided to switch to it.
Moreover, removing support for ruby tags allowed me to remove A LOT of legacy code and better support newer versions.

As mentioned in the README

> Please note this plugin will only generate furigana using the recommended bracket notation. Thus this plugin is incompatible with ruby tags generated by other tools.

**Comment by obynio** [comment]
We included an option to generate Furigana using ruby tags.
Download the latest plugin update to get it, then use the options below to enable it.

![furigana_menu](https://user-images.githubusercontent.com/2095991/150222394-7d28462f-f6dc-4de9-a082-7adb1b3159e1.png)
